### ISSUE TITLE
By-default cache-invalidation

### ISSUE THREAD

**Issue by bennn** [bennn/with-cache#1]
1. Fix the docs for `*current-cache-keys*`. They are confusing.
2. Make `'()` the "null" case for `*current-cache-keys*`, not `#f`
3. Add at least 2 default cache-invalidations:
   - One for the current package version (use `((get-info '("with-cache")) 'version)`)
   - One for if the cache was edited more recently than the current file

**Comment by LeifAndersen** [comment]
Re 2. Ya, although having `#f` as well is not the end of the world. It does match a lot of the Racket standard library.

Re 3b. Did you mean the other way around,if the current file was edited more recently than the cache?

Also, you might want to add 3c, like 3a, but for fasl/serialize versions, because if that changes the cache will also be invalidated.

**Comment by bennn** [comment]
Implemented `2` and `3a` in b775a57c394c5ac64bcc2eb84fc9ee141f8cc80d. Not sure how to do `3b`; I think `3c` is covered by `racket/fasl`.

Tried to fix `1` in dfd83486f4f3e1f012b1076876ccefc96c6b0e4f :)
